apiVersion: v1
kind: Service
metadata:
  name: ctfd-mysql
  labels:
    app: ctfd
spec:
  ports:
    - port: 3306
  selector:
    app: ctfd
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ctfd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-mysql
  labels:
    app: ctfd
spec:
  selector:
    matchLabels:
      app: ctfd
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ctfd
        tier: mysql
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - image: mariadb:10.4.2
          name: mysql
          args: [mysqld, --wait_timeout=28800]
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ctfd-mysql-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ctfd-mysql-credentials
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ctfd-mysql-credentials
                  key: database
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
