version: "3"

services:
  proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=wtctf.afnom.net
    command: "caddy reverse-proxy --from ${DOMAIN:-localhost} --to ctfd:8000"
    volumes:
      - .data/caddy_data:/data
      - .data/caddy_config:/config

  ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - db
    networks:
      default:
      internal:

  db:
    image: mariadb:10.4.12
    restart: unless-stopped
    command: [mysqld, --wait_timeout=28800]
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      internal:

  cache:
    image: redis:4
    restart: unless-stopped
    networks:
      internal:

networks:
  default:
  internal:
    internal: true
